### ISSUE TITLE
I'm having hard time to run your code 

### ISSUE THREAD

**Issue by aalzooke** [see--/P12-Semantic-Segmentation#3]
When i run this command i got the following error 
`python src/dump_predictions.py --model best-ep-38-val_iou-0.898-val_loss-0.064.hdf5 --fn-glob "video_jpgs/*.jpg" --crop 150,-100`

<img width="569" alt="Screen Shot 2019-04-25 at 11 37 57 PM" src="https://user-images.githubusercontent.com/14840496/56781990-2fc8b380-67b3-11e9-8029-58a3e09c80b9.png">

**Comment by see--** [comment]
I think this is a python2 problem. Can you try it with python3? Python2 will be deprecated soon.

**Comment by aalzooke** [comment]
ok let me test with python3

**Comment by aalzooke** [comment]
I got this error using python3 
<img width="567" alt="Screen Shot 2019-04-26 at 11 45 12 AM" src="https://user-images.githubusercontent.com/14840496/56819942-c7acb880-6818-11e9-972c-0b8bab4cb033.png">

**Comment by aalzooke** [comment]
Please let me know how to fix this issue

**Comment by aalzooke** [comment]
Solved it by installing latest keras
